name: user-service-ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "applications/microservices/user-service/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" \
          | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

      - name: Build and push image
        working-directory: applications/microservices/user-service
        run: |
          IMAGE="ghcr.io/${{ secrets.GHCR_USER }}/user-service:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Update GitOps manifests
        run: |
          IMAGE="ghcr.io/${{ secrets.GHCR_USER }}/user-service:${{ github.sha }}"

          # instalar yq
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

          # actualizar deployment base o overlay de prod
          cd gitops/environments/overlays/production/user-service
          yq -i '.images[0].name = "ghcr.io/'"${{ secrets.GHCR_USER }}"'/user-service"' kustomization.yaml || true
          yq -i '.images[0].newTag = "'"${GITHUB_SHA}"'"' kustomization.yaml || true

          cd -  # volver a la raíz

          git config user.name "ciclovida-bot"
          git config user.email "ciclovida-bot@example.com"

          git status
          git commit -am "chore: deploy user-service ${GITHUB_SHA}" || echo "No changes"
          git push https://x-access-token:${{ secrets.GHCR_TOKEN }}@github.com/Agustiniano/DevOps-Lifecycle.git
